package:
  version: "{{ load_setup_py_data().version }}"
  name: 'tamkin'

source:
  path: ../../

build:
  number: 0
  string: py{{ CONDA_PY }}_1
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - tamkin-driver = tamkin.driver:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - numpy >=1.0
    - scipy >=0.17.1
    - matplotlib >1.1
    - molmod >=1.4.5

test:
  imports:
    - tamkin

about:
  dev_url: https://github.com/molmod/tamkin
  description: TAMkin is a post-processing toolkit for normal mode analysis, thermochemistry and reaction kinetics.
  license: GNU General Public License v3 or later (GPLv3+)
  license_family: GPL3
  summary: TAMkin is a post-processing toolkit for normal mode analysis, thermochemistry and reaction kinetics.
  home: http://molmod.github.io/tamkin
  license_file: COPYING
  doc_url: http://molmod.github.io/tamkin

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
